name: technews
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3

  url_launcher: ^5.4.10
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.6
  firebase_messaging: ^6.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
     - family: TitleFont
       fonts:
         - asset: fonts/Graduate-Regular.ttf

